name: Deploy Portfolio

on:
  push:
    branches: ["main", "dev"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      # BU KISIM ÇOK KRİTİK: Mevcut deployment'ı bozmadan klasör oluşturur
      - name: Prepare Deployment Directory
        run: |
          mkdir -p final-deploy
          if [ "${{ github.ref_name }}" == "dev" ]; then
            mkdir -p final-deploy/dev
            cp -r out/* final-deploy/dev/
          else
            cp -r out/* final-deploy/
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: final-deploy  # Sadece out değil, hazırladığımız klasörü yüklüyoruz

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4